services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - ./logs:/usr/src/app/logs
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data: