filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/application.log
  fields:
    log_type: application
  fields_under_root: false

- type: log
  enabled: true
  paths:
    - /usr/share/filebeat/logs/requests.log
  fields:
    log_type: request
  fields_under_root: false

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 30
  permissions: 0644
